### ISSUE TITLE
Error while compiling

### ISSUE THREAD

**Issue by theshadowx** [msorvig/qt5-qtbase-nacl#8]
I'm working nowadays on a docker image of ubuntu 14.04 containing Qt5.4 compiled with NaCl, so that to make life easier for me and for others using Qt with NaCl.

Here is the github repository : https://github.com/theshadowx/Qt5.4_NaCl
Docker repository : https://registry.hub.docker.com/u/theshadowx/qt5.4-nacl/

My problem is that when I want to compile any project even the one in qtdeclarative (examples/nacl), I get these errors:

```
/opt/nacl_sdk/pepper_44/toolchain/linux_x86_newlib/bin/../lib/gcc/x86_64-nacl/4.4.3/../../../../x86_64-nacl/lib/../lib64/libpthread.a(nc_condvar_305aa45a.o): In function `pthread_condattr_init':
/mnt/data/b/build/slave/sdk-rel/build/src/native_client/src/untrusted/pthread/nc_condvar.c:114: multiple definition of `pthread_condattr_init'

/opt/QtNaCl_5.4/lib/libQt5Core.a(qfunctions_nacl.o):qfunctions_nacl.cpp:(.text+0xc0): first defined here
/opt/nacl_sdk/pepper_44/toolchain/linux_x86_newlib/bin/../lib/gcc/x86_64-nacl/4.4.3/../../../../x86_64-nacl/lib/../lib64/libpthread.a(nc_condvar_305aa45a.o): In function `pthread_condattr_destroy':
/mnt/data/b/build/slave/sdk-rel/build/src/native_client/src/untrusted/pthread/nc_condvar.c:118: multiple definition of `pthread_condattr_destroy'
/opt/QtNaCl_5.4/lib/libQt5Core.a(qfunctions_nacl.o):qfunctions_nacl.cpp:(.text+0xe0): first defined here
```

The NaCl SDK, I'm using, is the latest stable. 

Could you please take a look and let me know what's wrong ?

Thanks

**Comment by immesys** [comment]
I encountered this problem too, I believe the most elegant fix (one that does not preclude compiling with older pepper versions) is to change the offenders in qtbase/src/corelib/kernel/qfunctions_nacl.cpp to the following:

```
int pthread_condattr_init(pthread_condattr_t *) __attribute__((weak))
{
    return 0;
}

int pthread_condattr_destroy(pthread_condattr_t *attr) __attribute__((weak))
{
    return 0;
}
```

**Comment by theshadowx** [comment]
Ok, I'll make a patch and add it to the script.

BTW, have you tried it?

thanks

**Comment by immesys** [comment]
@theshadowx I am using it for a big project, yes! I discovered it from your YouTube video. I modified your Gist to work with Qt5.4 and am using that too.

**Comment by theshadowx** [comment]
@immesys ok so here is the patch: 

```
diff --git a/src/corelib/kernel/qfunctions_nacl.cpp b/src/corelib/kernel/qfunctions_nacl.cpp
index a5d86c9..a143d80 100644
--- a/src/corelib/kernel/qfunctions_nacl.cpp
+++ b/src/corelib/kernel/qfunctions_nacl.cpp
@@ -99,12 +99,12 @@ int pthread_attr_getinheritsched(const pthread_attr_t *, int *)
     return 0;
 }

-int pthread_condattr_init(pthread_condattr_t *)
+int pthread_condattr_init(pthread_condattr_t *) __attribute__((weak))
 {
     return 0;
 }

-int pthread_condattr_destroy(pthread_condattr_t *attr)
+int pthread_condattr_destroy(pthread_condattr_t *attr) __attribute__((weak))
 {
     return 0;
 }
@@ -308,12 +308,12 @@ int pthread_attr_setstacksize(pthread_attr_t *attr, size_t stacksize)
     return 0;
 }

-int pthread_condattr_init(pthread_condattr_t *)
+int pthread_condattr_init(pthread_condattr_t *) __attribute__((weak))
 {
     return 0;
 }

-int pthread_condattr_destroy(pthread_condattr_t *attr)
+int pthread_condattr_destroy(pthread_condattr_t *attr) __attribute__((weak))
 {
     return 0;
 }

diff --git a/src/corelib/kernel/qfunctions_nacl.h b/src/corelib/kernel/qfunctions_nacl.h
index 71201a6..41405da 100644
--- a/src/corelib/kernel/qfunctions_nacl.h
+++ b/src/corelib/kernel/qfunctions_nacl.h
@@ -73,8 +73,8 @@ int pthread_attr_getinheritsched(const pthread_attr_t *attr,
     int *inheritsched);

 // No condition variable attributes on pnacl, and no dummy pthread_condattr_* either
-int pthread_condattr_init(pthread_condattr_t *);
-int pthread_condattr_destroy(pthread_condattr_t *);
+int pthread_condattr_init(pthread_condattr_t *)  __attribute__((weak));
+int pthread_condattr_destroy(pthread_condattr_t *)  __attribute__((weak));

 pid_t getpid(void);
 uid_t geteuid(void);
```

Could you tell me if it's correct

thanks

**Comment by theshadowx** [comment]
I have changed the branch used in the script, and now I m using nacl-dev.

while building qtdeclarative, I receive this error 

```
[91m/opt/Qt5.4_src/qtsvg/src/svg/qsvggenerator.cpp: In member function 'void QSvgPaintEngine::saveGradientStops(QTextStream&, const QGradient*)':
/opt/Qt5.4_src/qtsvg/src/svg/qsvggenerator.cpp:258: error: 'PREMUL' was not declared in this scope[0m
[91m
[0m
[91m/opt/Qt5.4_src/qtsvg/src/svg/qsvggenerator.cpp:268: error: 'INV_PREMUL' was not declared in this scope[0m
```

here is the full log https://gist.githubusercontent.com/theshadowx/4bdfbbac1a520af9be2e/raw/9cf75e1381879dc3cc87f74003b07b51e3085f76/compilation.log

**Comment by msorvig** [comment]
Hi, looks like PREMUL has been replaced by qPremultiply in Qt 5.5, and that your qtsvg is still on 5.4.

Checking out the dev branch should fix the issue.

**Comment by theshadowx** [comment]
I have used nacl-dev branch, but I got the same error. Here is the script I'm using : https://github.com/theshadowx/Qt5.4_NaCl/blob/fromScript/QtNaCl_docker.sh

**Comment by msorvig** [comment]
What I did was "git grep PREMUL" in qtsvg and qtbase, for Qt 5.4 and dev. If your qtsvg checkout is still using it then it can't be up to date.

**Comment by theshadowx** [comment]
The results are : in qtbase uses qPremultiply but in qtsvg uses premul

As I used the nacl-dev in my script, that means the qtbase is not of version 5.4 but from dev branch of Qt5 repo (http://code.qt.io/cgit/qt/qtbase.git/log/?h=dev), is that right?

Which means I have to :

```
$ git clone git://code.qt.io/qt/qt5.git
$ cd qt5
$ git checkout 5.5    # or dev
$ ./init_repository
```

PS: Just wondering, you said that the modification premul --> premutliply has happened in Qt5.5 , how's possible that when I do `checkout 5.4` I find that qtbase using premutliply although it's from 5.4 branch ?

**Comment by msorvig** [comment]
Hi, I pushed an update to the nacl-5.4 now:
- Added "**attribute**((weak))" to qfunctions_nacl.h - we should not see this type of error again
- Updated README.md

To answer some of your questions: 

You need to make sure the submodules are at dev as well:
 `$ git submodule foreach 'git checkout dev'`

...but this will fail, since qtdeclarative 'dev' is now out of sync with qtbase 'nacl-dev'. README.md has a known-good sha1 for qtdeclarative. The alternative is to use the stable 5.4 branch.

For PREMUL, i think the transition happened in qtbase first, then the other modules.

**Comment by theshadowx** [comment]
Thanks for the Readme.

I have a question, is it mandatory to use pepper 42, as in my script, I download the latest stable version.

About PREMUL I have done a patch that replaces it with qPremultiply --> https://raw.githubusercontent.com/theshadowx/Qt5.4_NaCl/fromScript/qtsvg.patch

I have a question about which type of compilation should I do:   out of source / in source
Out of source takes a lot of space 6GB. As I'm doing a docker image, this amount of space is a lot.
that's why I'm asking this question.

**Comment by theshadowx** [comment]
So, 
I have now used pepper 42 with nacl-5.4 branch and in source compilation.
I stumble on this error : 

```
qttools/src/assistant/3rdparty/clucene/src/CLucene/store/Directory.h:80: error: 'snprintf' was not declared in this scope
```

From what I noticed, the error is result of C++11 is not being used because snprintf exists since C++11, even that in the command line that compile this file there is  -std=c++0x. However when I modify it to -std=gnu++0x , I don't receive this error.

## Using -std=c++0x

```
/opt/Qt5.4_src/qtbase# /opt/nacl_sdk/pepper_42/toolchain/linux_x86_newlib/bin/x86_64-nacl-g++ -m64 -c -include .pch/Qt5CLucene -pipe -O2 -fPIC -fvisibility=hidden -fvisibility-inlines-hidden -w -std=c++0x -DQ_OS_NACL_PEPPER -DQT_NO_MTDEV -DQT_NO_LIBUDEV -DQT_NO_EVDEV -DQT_BUILD_CLUCENE_LIB -DQT_BUILDING_QT -DQT_NO_CAST_TO_ASCII -DQT_ASCII_CAST_WARNINGS -DQT_MOC_COMPAT -DQT_USE_QSTRINGBUILDER -DQT_DEPRECATED_WARNINGS -DQT_DISABLE_DEPRECATED_BEFORE=0x050000 -D_BUILD_FOR_QT_ -DLUCENE_DISABLE_MEMTRACKING -D_LARGEFILE64_SOURCE -D_LARGEFILE_SOURCE -DQT_NO_DEBUG -DQT_CORE_LIB -I/opt/Qt5.4_src/qtbase/mkspecs/unsupported/nacl-x86-newlib-g++-64 -I/opt/Qt5.4_src/qttools/src/assistant/clucene -I/opt/nacl_sdk/pepper_42/include -I../../../include -I../../../include/QtCLucene -I../../../include/QtCLucene/5.4.3 -I../../../include/QtCLucene/5.4.3/QtCLucene -I/opt/Qt5.4_src/qttools/src/assistant/clucene -I/opt/Qt5.4_src/qttools/src/assistant -I/opt/Qt5.4_src/qttools/src/assistant/3rdparty/clucene/src/CLucene -I/opt/Qt5.4_src/qttools/src/assistant/3rdparty/clucene/src -I/opt/Qt5.4_src/qttools/src/assistant/3rdparty/clucene/src/CLucene/analysis -I/opt/Qt5.4_src/qttools/src/assistant/3rdparty/clucene/src/CLucene/analysis/standard -I/opt/Qt5.4_src/qttools/src/assistant/3rdparty/clucene/src/CLucene/config -I/opt/Qt5.4_src/qttools/src/assistant/3rdparty/clucene/src/CLucene/debug -I/opt/Qt5.4_src/qttools/src/assistant/3rdparty/clucene/src/CLucene/document -I/opt/Qt5.4_src/qttools/src/assistant/3rdparty/clucene/src/CLucene/index -I/opt/Qt5.4_src/qttools/src/assistant/3rdparty/clucene/src/CLucene/queryParser -I/opt/Qt5.4_src/qttools/src/assistant/3rdparty/clucene/src/CLucene/search -I/opt/Qt5.4_src/qttools/src/assistant/3rdparty/clucene/src/CLucene/store -I/opt/Qt5.4_src/qttools/src/assistant/3rdparty/clucene/src/CLucene/util -I/opt/Qt5.4_src/qtbase/qtbase/include -I/opt/Qt5.4_src/qtbase/qtbase/include/QtCore -I.moc -I. -o .obj/StdHeader.o /opt/Qt5.4_src/qttools/src/assistant/3rdparty/clucene/src/CLucene/StdHeader.cpp
Assembler messages:
Fatal error: can't create .obj/StdHeader.o: No such file or directory
cc1plus: error: .pch/Qt5CLucene: No such file or directory
In file included from /opt/Qt5.4_src/qttools/src/assistant/3rdparty/clucene/src/CLucene/index/IndexReader.h:18,
                 from /opt/Qt5.4_src/qttools/src/assistant/3rdparty/clucene/src/CLucene/search/Sort.h:14,
                 from /opt/Qt5.4_src/qttools/src/assistant/3rdparty/clucene/src/CLucene/StdHeader.cpp:12:
/opt/Qt5.4_src/qttools/src/assistant/3rdparty/clucene/src/CLucene/store/Directory.h: In member function 'virtual bool lucene::store::Directory::deleteFile(const QString&, bool)':
/opt/Qt5.4_src/qttools/src/assistant/3rdparty/clucene/src/CLucene/store/Directory.h:81: error: 'snprintf' was not declared in this scope
```

## Using -std=gnu++0x

```
/opt/Qt5.4_src/qtbase# /opt/nacl_sdk/pepper_42/toolchain/linux_x86_newlib/bin/x86_64-nacl-g++ -m64 -c -include .pch/Qt5CLucene -pipe -O2 -fPIC -fvisibility=hidden -fvisibility-inlines-hidden -w -std=gnu++0x -DQ_OS_NACL_PEPPER -DQT_NO_MTDEV -DQT_NO_LIBUDEV -DQT_NO_EVDEV -DQT_BUILD_CLUCENE_LIB -DQT_BUILDING_QT -DQT_NO_CAST_TO_ASCII -DQT_ASCII_CAST_WARNINGS -DQT_MOC_COMPAT -DQT_USE_QSTRINGBUILDER -DQT_DEPRECATED_WARNINGS -DQT_DISABLE_DEPRECATED_BEFORE=0x050000 -D_BUILD_FOR_QT_ -DLUCENE_DISABLE_MEMTRACKING -D_LARGEFILE64_SOURCE -D_LARGEFILE_SOURCE -DQT_NO_DEBUG -DQT_CORE_LIB -I/opt/Qt5.4_src/qtbase/mkspecs/unsupported/nacl-x86-newlib-g++-64 -I/opt/Qt5.4_src/qttools/src/assistant/clucene -I/opt/nacl_sdk/pepper_42/include -I../../../include -I../../../include/QtCLucene -I../../../include/QtCLucene/5.4.3 -I../../../include/QtCLucene/5.4.3/QtCLucene -I/opt/Qt5.4_src/qttools/src/assistant/clucene -I/opt/Qt5.4_src/qttools/src/assistant -I/opt/Qt5.4_src/qttools/src/assistant/3rdparty/clucene/src/CLucene -I/opt/Qt5.4_src/qttools/src/assistant/3rdparty/clucene/src -I/opt/Qt5.4_src/qttools/src/assistant/3rdparty/clucene/src/CLucene/analysis -I/opt/Qt5.4_src/qttools/src/assistant/3rdparty/clucene/src/CLucene/analysis/standard -I/opt/Qt5.4_src/qttools/src/assistant/3rdparty/clucene/src/CLucene/config -I/opt/Qt5.4_src/qttools/src/assistant/3rdparty/clucene/src/CLucene/debug -I/opt/Qt5.4_src/qttools/src/assistant/3rdparty/clucene/src/CLucene/document -I/opt/Qt5.4_src/qttools/src/assistant/3rdparty/clucene/src/CLucene/index -I/opt/Qt5.4_src/qttools/src/assistant/3rdparty/clucene/src/CLucene/queryParser -I/opt/Qt5.4_src/qttools/src/assistant/3rdparty/clucene/src/CLucene/search -I/opt/Qt5.4_src/qttools/src/assistant/3rdparty/clucene/src/CLucene/store -I/opt/Qt5.4_src/qttools/src/assistant/3rdparty/clucene/src/CLucene/util -I/opt/Qt5.4_src/qtbase/qtbase/include -I/opt/Qt5.4_src/qtbase/qtbase/include/QtCore -I.moc -I. -o .obj/StdHeader.o /opt/Qt5.4_src/qttools/src/assistant/3rdparty/clucene/src/CLucene/StdHeader.cpp
Assembler messages:
Fatal error: can't create .obj/StdHeader.o: No such file or directory
cc1plus: error: .pch/Qt5CLucene: No such file or directory
```

**Comment by msorvig** [comment]
qttools is not supported - "make module-qtquickcontrols" at the top-level Qt build directory should build the supported set of modules.

**Comment by msorvig** [comment]
Using pepper_42 is not mandatory, but I recommend you start out with a "known good" configuration (including the pepper version), reproduce that build successfully, and then make changes as needed for your use case.

For the build types I recommend out-of-source builds, configured with "-release -nomake examples -nomake tests." That should cut down the build size significantly from 6GB.

Interesting that you are creating a docker image! I experimented a bit with using Vagrant but decided against it due to increased compile time when building Qt. (though this might be a lesser concern for Qt _users_ who seldom build all of Qt.)
